name:         self-extract
version:      0.4.1
license:      BSD3
author:       Brandon Chinn <brandonchinn178@gmail.com>
maintainer:   Brandon Chinn <brandonchinn178@gmail.com>
category:     Distribution
synopsis:     A Haskell library to make self-extracting executables
description:  A Haskell library to make self-extracting executables.
extra-doc-files:
  - CHANGELOG.md
  - README.md

github: brandonchinn178/self-extract

flags:
  dev:
    description:  Turn on development settings.
    manual:       true
    default:      false

ghc-options: -Wall
when:
  - condition: flag(dev)
    ghc-options: -Werror
  - condition: impl(ghc >= 8.0)
    ghc-options:
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wnoncanonical-monad-instances
      - -Wnoncanonical-monadfail-instances

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - Cabal >= 2.0 && < 3
    - binary >= 0.8.5 && < 0.9
    - bytestring >= 0.10.8 && < 0.11
    - extra >= 1.6 && < 1.7
    - file-embed >= 0.0.10 && < 0.1
    - path >= 0.6 && < 0.7
    - path-io >= 1.3 && < 1.5
    - unix-compat >= 0.5 && < 0.6
    - ztar >= 1.0 && < 1.1

executables:
  self-bundle:
    main:      Bundle.hs
    source-dirs:  exe
    dependencies:
      - base
      - self-extract
