resolver: lts-21.0

extra-deps:
- example/cabal
- ztar-1.0.1
# https://github.com/jaspervdj/stylish-haskell/pull/227
- git: https://github.com/LeapYear/stylish-haskell.git
  commit: 6861e8c24b9f32dcbffe9762d0807fdaff3fecf4
